services:
  flowmetrix-ai-chat-db:
    image: postgres:16
    container_name: serav-cv-ai-chat-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: cv
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

#  podman compose up -d
#  podman compose down
