spring:
  application:
    name: serav-cv-assistant
#
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}
    username: ${POSTGRESQL_ADDON_USER}
    password: ${POSTGRESQL_ADDON_PASSWORD}
    hikari:
      schema: cv_assistant

  #
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    openai:
      api-key: ${TOGETHER_AI_API_KEY}
      base-url: https://api.together.xyz
      chat:
        options:
          model: meta-llama/Llama-3.3-70B-Instruct-Turbo
          temperature: 0.7
          max-tokens: 1024
          top-p: 0.9
  #
  sql:
    init:
      mode: always

  threads:
    virtual:
      enabled: true

server:
  port: 8080
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:5m}

app:
  skills-unpack: ${SKILLS_ZIP_UNPACK}
  console-label: ${CONSOLE_LABEL}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    username: ${CC_METRICS_PROMETHEUS_USER}
    password: ${CC_METRICS_PROMETHEUS_PASSWORD}
  otlp:
    metrics:
      export:
        url: ${GRAFANA_OTLP_URL}
        headers:
          Authorization: Basic ${GRAFANA_OTLP_TOKEN}
        step: 60s

logging:
  level:
    root: INFO
    de.serav.cv.assistant: DEBUG
#
vaadin:
  productionMode: true
  frontend:
    hotdeploy: false
