spring.application.name=flowmetrix-ai-chat
#
spring.datasource.url=jdbc:postgresql://${vcap.services.flowmetrix-ai-chat-db.credentials.host}:${vcap.services.flowmetrix-ai-chat-db.credentials.port}/${vcap.services.flowmetrix-ai-chat-db.credentials.name}
spring.datasource.username=${vcap.services.flowmetrix-ai-chat-db.credentials.username}
spring.datasource.password=${vcap.services.flowmetrix-ai-chat-db.credentials.password}
spring.datasource.driver-class-name=org.postgresql.Driver




spring.ai.chat.memory.repository.jdbc.initialize-schema=always

#
spring.threads.virtual.enabled=true
#

#using the GitHub Models endpoint (models.inference.ai.azure.com) instead of OpenAI,
spring.ai.openai.base-url=https://models.inference.ai.azure.com
spring.ai.openai.api-key=${vcap.services.flowmetrix-ai-chat-creds.credentials.api-key}
spring.ai.openai.chat.options.model=gpt-4.1-mini
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.embedding.embeddings-path=/embeddings

#
vaadin.productionMode=true
vaadin.frontend.hotdeploy=false

#
logging.level.root=INFO
logging.level.de.serav.flowmetrix=DEBUG


